### DISCUSSION TITLE
[charts][sda-mq] Issue with connecting to CEGA

### DISCUSSION THREAD

**Discussion by josefhandl** [neicnordic/sensitive-data-archive#792] [Q&A] [answered]
Hello,

I would like to ask you for help with our SDA installation and configuration. I am deploying the SDA but encountered a problem with MQ component. The MQ Pod fails to connect to CEGA due to invalid options:
```
Shovel 'to_cega' failed to connect (URI: amqps://rabbitmq.test.ega-archive.org:5671/czech): {options,incompatible,[{verify,verify_peer},{cacerts,undefined}]}
Shovel 'to_cega' has no more URIs to try for connection
Shovel 'to_cega' could not connect to destination: error failed_to_connect_using_provided_uris
...
Federation queue 'from_cega' in vhost 'sda' did not connect to queue 'to_fega' in vhost 'czech' on amqps://rabbitmq.test.ega-archive.org:5671/czech. Reason: {error,{options,incompatible,[{verify,verify_peer},{cacerts,undefined}]}}
```

Unfortunately, event though I set `global.tls.caCert` and `global.tls.issuer` (k8s-local self-signed CA), the setting is not propagated to the *Pod*. I verified that the var `RABBITMQ_SERVER_CACERT:  /etc/rabbitmq/tls/ca.crt` is set and the file exists, but the problem with `Reason: {error,{options,incompatible,[{verify,verify_peer},{cacerts,undefined}]}}` is still present.

I also tried to use `global.tls.clusterIssuer: letsencrypt-prod` instead of the self-signed `issuer`, but the `sda-mq-certs` *Certificate* resource seems to be incompattible with public CA:

```
Warning  Failed     82s   cert-manager-certificates-issuing          The certificate request has failed to complete and will be retried: Failed to wait for order resource "sda-mq-1-2066896948" to become ready: order is in "errored" state: Failed to create Order: 400 urn:ietf:params:acme:error:unsupportedIdentifier: NewOrder request included invalid non-DNS type identifier: type "ip", value "127.0.0.1"
```

There is a part of the `values.yaml` file:
```
global:
  adminUser: user
  adminPassword: aaaaaaaa
  ingress:
    # extra annotations for the ingress
    annotations:
      kubernetes.io/tls-acme: "true"
    hostName: {} # "mq.fega.cloud.e-infra.cz"
    ingressClassName: "nginx"
    issuer: ""
    clusterIssuer: "letsencrypt-prod"
    # If the certificates is generated by external providers
    # the secrets containing them needs to be created manually.
    secretName: "mq-fega-cloud-e-infra-cz"
  tls:
    enabled: true
    issuer: "ega-ca-ns-issuer"
    #clusterIssuer: "letsencrypt-prod"
    secretName: ""
    certName: tls.crt
    keyName: tls.key
    caCert: ca.crt
    verifyPeer: true
  vhost: "sda"

# Upstream shovel recipient
# only used in a federated setup
  shovel:
    host: rabbitmq.test.ega-archive.org
    pass: "aaaaaaaa"
    port: 5671
    user: user
    vhost: czech
```

Thank you
