### ISSUE TITLE
Implement re-encryption

### ISSUE THREAD

**Issue by teemukataja** [neicnordic/sensitive-data-archive#366]
If a user sends a public key, re-encrypt the data
related params:
```
        - name: Public-Key
          in: header
          description: Public Encryption key
          required: false
          schema:
            type: string
        - name: destinationFormat
          in: query
          description: destinationFormat
          required: false
          schema:
            type: string
            default: plain | crypt4gh
```

Also take a look at https://github.com/neicnordic/sda-download/blob/0aa5af3ce690a610c5c2b369dd9d0ef8d58468d7/internal/database/database.go#L173-L178
